/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Address,
  City,
  Country
} from '../../model';


export const getGetApiAddressIdResponseCountryMock = (overrideResponse: Partial<Country> = {}): Country => ({...{id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), isoCode: faker.string.alpha({length: {min: 10, max: 20}}), phonePrefix: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse});

export const getGetApiAddressIdResponseCityMock = (overrideResponse: Partial<City> = {}): City => ({...{id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), region: faker.string.alpha({length: {min: 10, max: 20}}), countryId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), country: faker.helpers.arrayElement([faker.helpers.arrayElement([null,{...getGetApiAddressIdResponseCountryMock()},]), undefined])}, ...overrideResponse});

export const getGetApiAddressIdResponseMock = (overrideResponse: Partial< Address > = {}): Address => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), street: faker.string.alpha({length: {min: 10, max: 20}}), buildingNumber: faker.string.alpha({length: {min: 10, max: 20}}), apartmentNumber: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), zipCode: faker.string.alpha({length: {min: 10, max: 20}}), latitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),faker.string.alpha({length: {min: 10, max: 20}}),]), undefined]), longitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),faker.string.alpha({length: {min: 10, max: 20}}),]), undefined]), cityId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), city: faker.helpers.arrayElement([faker.helpers.arrayElement([null,{...getGetApiAddressIdResponseCityMock()},]), undefined]), ...overrideResponse})

export const getPostApiAddressResponseCountryMock = (overrideResponse: Partial<Country> = {}): Country => ({...{id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), isoCode: faker.string.alpha({length: {min: 10, max: 20}}), phonePrefix: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse});

export const getPostApiAddressResponseCityMock = (overrideResponse: Partial<City> = {}): City => ({...{id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), region: faker.string.alpha({length: {min: 10, max: 20}}), countryId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), country: faker.helpers.arrayElement([faker.helpers.arrayElement([null,{...getPostApiAddressResponseCountryMock()},]), undefined])}, ...overrideResponse});

export const getPostApiAddressResponseMock = (overrideResponse: Partial< Address > = {}): Address => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), street: faker.string.alpha({length: {min: 10, max: 20}}), buildingNumber: faker.string.alpha({length: {min: 10, max: 20}}), apartmentNumber: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), zipCode: faker.string.alpha({length: {min: 10, max: 20}}), latitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),faker.string.alpha({length: {min: 10, max: 20}}),]), undefined]), longitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),faker.string.alpha({length: {min: 10, max: 20}}),]), undefined]), cityId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), city: faker.helpers.arrayElement([faker.helpers.arrayElement([null,{...getPostApiAddressResponseCityMock()},]), undefined]), ...overrideResponse})

export const getGetApiAddressGetAllResponseCountryMock = (overrideResponse: Partial<Country> = {}): Country => ({...{id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), isoCode: faker.string.alpha({length: {min: 10, max: 20}}), phonePrefix: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse});

export const getGetApiAddressGetAllResponseCityMock = (overrideResponse: Partial<City> = {}): City => ({...{id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), region: faker.string.alpha({length: {min: 10, max: 20}}), countryId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), country: faker.helpers.arrayElement([faker.helpers.arrayElement([null,{...getGetApiAddressGetAllResponseCountryMock()},]), undefined])}, ...overrideResponse});

export const getGetApiAddressGetAllResponseMock = (): Address[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), street: faker.string.alpha({length: {min: 10, max: 20}}), buildingNumber: faker.string.alpha({length: {min: 10, max: 20}}), apartmentNumber: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), zipCode: faker.string.alpha({length: {min: 10, max: 20}}), latitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),faker.string.alpha({length: {min: 10, max: 20}}),]), undefined]), longitude: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),faker.string.alpha({length: {min: 10, max: 20}}),]), undefined]), cityId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), city: faker.helpers.arrayElement([faker.helpers.arrayElement([null,{...getGetApiAddressGetAllResponseCityMock()},]), undefined])})))


export const getGetApiAddressIdMockHandler = (overrideResponse?: Address | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Address> | Address), options?: RequestHandlerOptions) => {
  return http.get('*/api/Address/:id', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiAddressIdResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}

export const getPutApiAddressIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/api/Address/:id', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getDeleteApiAddressIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/Address/:id', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getPostApiAddressMockHandler = (overrideResponse?: Address | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Address> | Address), options?: RequestHandlerOptions) => {
  return http.post('*/api/Address', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiAddressResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}

export const getGetApiAddressGetAllMockHandler = (overrideResponse?: Address[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Address[]> | Address[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/Address/GetAll', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiAddressGetAllResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}
export const getAddressMock = () => [
  getGetApiAddressIdMockHandler(),
  getPutApiAddressIdMockHandler(),
  getDeleteApiAddressIdMockHandler(),
  getPostApiAddressMockHandler(),
  getGetApiAddressGetAllMockHandler()]
