/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  Address,
  CreateAddressDto,
  UpdateAddressDto
} from '../../model';

import { customInstance } from '../../axiosConfig';



  export const getAddress = () => {
const getApiAddressId = (
    id: string,
 ) => {
      return customInstance<Address>(
      {url: `/api/Address/${id}`, method: 'GET'
    },
      );
    }
  const putApiAddressId = (
    id: string,
    updateAddressDto: UpdateAddressDto,
 ) => {
      return customInstance<void>(
      {url: `/api/Address/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateAddressDto
    },
      );
    }
  const deleteApiAddressId = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/api/Address/${id}`, method: 'DELETE'
    },
      );
    }
  const postApiAddress = (
    createAddressDto: CreateAddressDto,
 ) => {
      return customInstance<Address>(
      {url: `/api/Address`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAddressDto
    },
      );
    }
  const getApiAddressGetAll = (
    
 ) => {
      return customInstance<Address[]>(
      {url: `/api/Address/GetAll`, method: 'GET'
    },
      );
    }
  return {getApiAddressId,putApiAddressId,deleteApiAddressId,postApiAddress,getApiAddressGetAll}};
export type GetApiAddressIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAddress>['getApiAddressId']>>>
export type PutApiAddressIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAddress>['putApiAddressId']>>>
export type DeleteApiAddressIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAddress>['deleteApiAddressId']>>>
export type PostApiAddressResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAddress>['postApiAddress']>>>
export type GetApiAddressGetAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAddress>['getApiAddressGetAll']>>>
