/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Address,
  CreateAddressDto,
  UpdateAddressDto
} from '../../model';




  export const getAddress = () => {
const getApiAddressGetAll = <TData = AxiosResponse<Address[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Address/GetAll`,options
    );
  }
const getApiAddressGetAdressId = <TData = AxiosResponse<Address>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Address/GetAdress/${id}`,options
    );
  }
const postApiAddressCreate = <TData = AxiosResponse<Address>>(
    createAddressDto: CreateAddressDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/Address/Create`,
      createAddressDto,options
    );
  }
const putApiAddressUpdateId = <TData = AxiosResponse<void>>(
    id: string,
    updateAddressDto: UpdateAddressDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/Address/Update/${id}`,
      updateAddressDto,options
    );
  }
const deleteApiAddressDeleteId = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/Address/Delete/${id}`,options
    );
  }
return {getApiAddressGetAll,getApiAddressGetAdressId,postApiAddressCreate,putApiAddressUpdateId,deleteApiAddressDeleteId}};
export type GetApiAddressGetAllResult = AxiosResponse<Address[]>
export type GetApiAddressGetAdressIdResult = AxiosResponse<Address>
export type PostApiAddressCreateResult = AxiosResponse<Address>
export type PutApiAddressUpdateIdResult = AxiosResponse<void>
export type DeleteApiAddressDeleteIdResult = AxiosResponse<void>
