/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Address,
  CreateAddressDto,
  UpdateAddressDto
} from '../../model';




  export const getAddress = () => {
const getApiAddressId = <TData = AxiosResponse<Address>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Address/${id}`,options
    );
  }
const putApiAddressId = <TData = AxiosResponse<void>>(
    id: string,
    updateAddressDto: UpdateAddressDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/Address/${id}`,
      updateAddressDto,options
    );
  }
const deleteApiAddressId = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/Address/${id}`,options
    );
  }
const postApiAddress = <TData = AxiosResponse<Address>>(
    createAddressDto: CreateAddressDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/Address`,
      createAddressDto,options
    );
  }
const getApiAddressGetAll = <TData = AxiosResponse<Address[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Address/GetAll`,options
    );
  }
return {getApiAddressId,putApiAddressId,deleteApiAddressId,postApiAddress,getApiAddressGetAll}};
export type GetApiAddressIdResult = AxiosResponse<Address>
export type PutApiAddressIdResult = AxiosResponse<void>
export type DeleteApiAddressIdResult = AxiosResponse<void>
export type PostApiAddressResult = AxiosResponse<Address>
export type GetApiAddressGetAllResult = AxiosResponse<Address[]>
