/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CountryDto,
  CreateCountryDto,
  UpdateCountryDto
} from '../../model';




  export const getCountry = () => {
const getApiCountryGetAll = <TData = AxiosResponse<CountryDto[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Country/GetAll`,options
    );
  }
const getApiCountryId = <TData = AxiosResponse<CountryDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Country/${id}`,options
    );
  }
const putApiCountryId = <TData = AxiosResponse<void>>(
    id: string,
    updateCountryDto: UpdateCountryDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/Country/${id}`,
      updateCountryDto,options
    );
  }
const deleteApiCountryId = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/Country/${id}`,options
    );
  }
const postApiCountry = <TData = AxiosResponse<CountryDto>>(
    createCountryDto: CreateCountryDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/Country`,
      createCountryDto,options
    );
  }
return {getApiCountryGetAll,getApiCountryId,putApiCountryId,deleteApiCountryId,postApiCountry}};
export type GetApiCountryGetAllResult = AxiosResponse<CountryDto[]>
export type GetApiCountryIdResult = AxiosResponse<CountryDto>
export type PutApiCountryIdResult = AxiosResponse<void>
export type DeleteApiCountryIdResult = AxiosResponse<void>
export type PostApiCountryResult = AxiosResponse<CountryDto>
