/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CountryDto
} from '../../model';


export const getGetApiCountryGetAllResponseMock = (): CountryDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), isoCode: faker.string.alpha({length: {min: 10, max: 20}}), phonePrefix: faker.string.alpha({length: {min: 10, max: 20}})})))

export const getGetApiCountryIdResponseMock = (overrideResponse: Partial< CountryDto > = {}): CountryDto => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), isoCode: faker.string.alpha({length: {min: 10, max: 20}}), phonePrefix: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getPostApiCountryResponseMock = (overrideResponse: Partial< CountryDto > = {}): CountryDto => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), isoCode: faker.string.alpha({length: {min: 10, max: 20}}), phonePrefix: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getGetApiCountryGetAllMockHandler = (overrideResponse?: CountryDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CountryDto[]> | CountryDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/Country/GetAll', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiCountryGetAllResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}

export const getGetApiCountryIdMockHandler = (overrideResponse?: CountryDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CountryDto> | CountryDto), options?: RequestHandlerOptions) => {
  return http.get('*/api/Country/:id', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiCountryIdResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}

export const getPutApiCountryIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/api/Country/:id', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getDeleteApiCountryIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/Country/:id', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getPostApiCountryMockHandler = (overrideResponse?: CountryDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CountryDto> | CountryDto), options?: RequestHandlerOptions) => {
  return http.post('*/api/Country', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiCountryResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}
export const getCountryMock = () => [
  getGetApiCountryGetAllMockHandler(),
  getGetApiCountryIdMockHandler(),
  getPutApiCountryIdMockHandler(),
  getDeleteApiCountryIdMockHandler(),
  getPostApiCountryMockHandler()]
