/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  CountryDto,
  CreateCountryDto,
  UpdateCountryDto
} from '../../model';

import { customInstance } from '../../axiosConfig';



  export const getCountry = () => {
const getApiCountryGetAll = (
    
 ) => {
      return customInstance<CountryDto[]>(
      {url: `/api/Country/GetAll`, method: 'GET'
    },
      );
    }
  const getApiCountryId = (
    id: string,
 ) => {
      return customInstance<CountryDto>(
      {url: `/api/Country/${id}`, method: 'GET'
    },
      );
    }
  const putApiCountryId = (
    id: string,
    updateCountryDto: UpdateCountryDto,
 ) => {
      return customInstance<void>(
      {url: `/api/Country/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCountryDto
    },
      );
    }
  const deleteApiCountryId = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/api/Country/${id}`, method: 'DELETE'
    },
      );
    }
  const postApiCountry = (
    createCountryDto: CreateCountryDto,
 ) => {
      return customInstance<CountryDto>(
      {url: `/api/Country`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCountryDto
    },
      );
    }
  return {getApiCountryGetAll,getApiCountryId,putApiCountryId,deleteApiCountryId,postApiCountry}};
export type GetApiCountryGetAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCountry>['getApiCountryGetAll']>>>
export type GetApiCountryIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCountry>['getApiCountryId']>>>
export type PutApiCountryIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCountry>['putApiCountryId']>>>
export type DeleteApiCountryIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCountry>['deleteApiCountryId']>>>
export type PostApiCountryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCountry>['postApiCountry']>>>
