/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  PizzaFiltersDto
} from '../../model';




  export const getLookUp = () => {
const getApiLookUpFilters = <TData = AxiosResponse<PizzaFiltersDto>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/LookUp/filters`,options
    );
  }
return {getApiLookUpFilters}};
export type GetApiLookUpFiltersResult = AxiosResponse<PizzaFiltersDto>
