/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetApiLookUpEnumAllParams,
  GetApiLookUpEnumParams,
  LookUpItemDto,
  PizzaFiltersDto
} from '../../model';

import { customInstance } from '../../axiosConfig';



  export const getLookUp = () => {
const getApiLookUpFilters = (
    
 ) => {
      return customInstance<PizzaFiltersDto>(
      {url: `/api/LookUp/filters`, method: 'GET'
    },
      );
    }
  const getApiLookUpEnum = (
    params?: GetApiLookUpEnumParams,
 ) => {
      return customInstance<LookUpItemDto>(
      {url: `/api/LookUp/enum`, method: 'GET',
        params
    },
      );
    }
  const getApiLookUpEnumAll = (
    params?: GetApiLookUpEnumAllParams,
 ) => {
      return customInstance<LookUpItemDto[]>(
      {url: `/api/LookUp/enum/all`, method: 'GET',
        params
    },
      );
    }
  return {getApiLookUpFilters,getApiLookUpEnum,getApiLookUpEnumAll}};
export type GetApiLookUpFiltersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLookUp>['getApiLookUpFilters']>>>
export type GetApiLookUpEnumResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLookUp>['getApiLookUpEnum']>>>
export type GetApiLookUpEnumAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLookUp>['getApiLookUpEnumAll']>>>
