/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  PizzeriaDetailsDto
} from '../../model';


export const getGetApiPizzeriaIdResponseMock = (overrideResponse: Partial< PizzeriaDetailsDto > = {}): PizzeriaDetailsDto => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), brandName: faker.string.alpha({length: {min: 10, max: 20}}), phoneNumber: faker.string.alpha({length: {min: 10, max: 20}}), deliveryCost: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),faker.string.alpha({length: {min: 10, max: 20}}),]), undefined]), minOrderAmount: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),faker.string.alpha({length: {min: 10, max: 20}}),]), undefined]), serviceFee: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),faker.string.alpha({length: {min: 10, max: 20}}),]), undefined]), averagePreparationTimeMinutes: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),faker.string.alpha({length: {min: 10, max: 20}}),]), undefined]), isOpen: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), activeMenuId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.uuid(), null]), undefined]), address: {street: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), city: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), fullAddress: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, ...overrideResponse})


export const getPostApiPizzeriaMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/Pizzeria', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getGetApiPizzeriaIdMockHandler = (overrideResponse?: PizzeriaDetailsDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PizzeriaDetailsDto> | PizzeriaDetailsDto), options?: RequestHandlerOptions) => {
  return http.get('*/api/Pizzeria/:id', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiPizzeriaIdResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}
export const getPizzeriaMock = () => [
  getPostApiPizzeriaMockHandler(),
  getGetApiPizzeriaIdMockHandler()]
