/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreatePizzeriaDto,
  PizzeriaDetailsDto
} from '../../model';

import { customInstance } from '../../axiosConfig';



  export const getPizzeria = () => {
const postApiPizzeria = (
    createPizzeriaDto: CreatePizzeriaDto,
 ) => {
      return customInstance<void>(
      {url: `/api/Pizzeria`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPizzeriaDto
    },
      );
    }
  const getApiPizzeriaId = (
    id: string,
 ) => {
      return customInstance<PizzeriaDetailsDto>(
      {url: `/api/Pizzeria/${id}`, method: 'GET'
    },
      );
    }
  return {postApiPizzeria,getApiPizzeriaId}};
export type PostApiPizzeriaResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPizzeria>['postApiPizzeria']>>>
export type GetApiPizzeriaIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPizzeria>['getApiPizzeriaId']>>>
