/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreatePizzeriaDto,
  PizzeriaDetailsDto
} from '../../model';




  export const getPizzeria = () => {
const postApiPizzeria = <TData = AxiosResponse<void>>(
    createPizzeriaDto: CreatePizzeriaDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/Pizzeria`,
      createPizzeriaDto,options
    );
  }
const getApiPizzeriaId = <TData = AxiosResponse<PizzeriaDetailsDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Pizzeria/${id}`,options
    );
  }
return {postApiPizzeria,getApiPizzeriaId}};
export type PostApiPizzeriaResult = AxiosResponse<void>
export type GetApiPizzeriaIdResult = AxiosResponse<PizzeriaDetailsDto>
