/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateMenuDto,
  MenuDetailsDto,
  MenuListItemDto
} from '../../model';




  export const getMenu = () => {
const getApiMenuId = <TData = AxiosResponse<MenuDetailsDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Menu/${id}`,options
    );
  }
const deleteApiMenuId = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/Menu/${id}`,options
    );
  }
const postApiMenuCreate = <TData = AxiosResponse<void>>(
    createMenuDto: CreateMenuDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/Menu/Create`,
      createMenuDto,options
    );
  }
const putApiMenuIdActivate = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/Menu/${id}/activate`,undefined,options
    );
  }
const getApiMenuGetAllMenusPizzeriaId = <TData = AxiosResponse<MenuListItemDto[]>>(
    pizzeriaId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Menu/GetAllMenus/${pizzeriaId}`,options
    );
  }
return {getApiMenuId,deleteApiMenuId,postApiMenuCreate,putApiMenuIdActivate,getApiMenuGetAllMenusPizzeriaId}};
export type GetApiMenuIdResult = AxiosResponse<MenuDetailsDto>
export type DeleteApiMenuIdResult = AxiosResponse<void>
export type PostApiMenuCreateResult = AxiosResponse<void>
export type PutApiMenuIdActivateResult = AxiosResponse<void>
export type GetApiMenuGetAllMenusPizzeriaIdResult = AxiosResponse<MenuListItemDto[]>
