/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateMenuDto,
  MenuDetailsDto,
  MenuListItemDto
} from '../../model';

import { customInstance } from '../../axiosConfig';



  export const getMenu = () => {
const getApiMenuId = (
    id: string,
 ) => {
      return customInstance<MenuDetailsDto>(
      {url: `/api/Menu/${id}`, method: 'GET'
    },
      );
    }
  const deleteApiMenuId = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/api/Menu/${id}`, method: 'DELETE'
    },
      );
    }
  const postApiMenuCreate = (
    createMenuDto: CreateMenuDto,
 ) => {
      return customInstance<void>(
      {url: `/api/Menu/Create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createMenuDto
    },
      );
    }
  const putApiMenuIdActivate = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/api/Menu/${id}/activate`, method: 'PUT'
    },
      );
    }
  const getApiMenuGetAllMenusPizzeriaId = (
    pizzeriaId: string,
 ) => {
      return customInstance<MenuListItemDto[]>(
      {url: `/api/Menu/GetAllMenus/${pizzeriaId}`, method: 'GET'
    },
      );
    }
  return {getApiMenuId,deleteApiMenuId,postApiMenuCreate,putApiMenuIdActivate,getApiMenuGetAllMenusPizzeriaId}};
export type GetApiMenuIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMenu>['getApiMenuId']>>>
export type DeleteApiMenuIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMenu>['deleteApiMenuId']>>>
export type PostApiMenuCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMenu>['postApiMenuCreate']>>>
export type PutApiMenuIdActivateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMenu>['putApiMenuIdActivate']>>>
export type GetApiMenuGetAllMenusPizzeriaIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMenu>['getApiMenuGetAllMenusPizzeriaId']>>>
