/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  LoginDto,
  LoginResponseDto,
  RegisterDto
} from '../../model';

import { customInstance } from '../../axiosConfig';



  export const getAuth = () => {
const postApiAuthRegister = (
    registerDto: RegisterDto,
 ) => {
      return customInstance<void>(
      {url: `/api/Auth/Register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerDto
    },
      );
    }
  const postApiAuthLogin = (
    loginDto: LoginDto,
 ) => {
      return customInstance<LoginResponseDto>(
      {url: `/api/Auth/Login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginDto
    },
      );
    }
  return {postApiAuthRegister,postApiAuthLogin}};
export type PostApiAuthRegisterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['postApiAuthRegister']>>>
export type PostApiAuthLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['postApiAuthLogin']>>>
