/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  LoginDto,
  RegisterDto
} from '../../model';




  export const getAuth = () => {
const postApiAuthRegister = <TData = AxiosResponse<void>>(
    registerDto: RegisterDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/Auth/Register`,
      registerDto,options
    );
  }
const postApiAuthLogin = <TData = AxiosResponse<void>>(
    loginDto: LoginDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/Auth/Login`,
      loginDto,options
    );
  }
return {postApiAuthRegister,postApiAuthLogin}};
export type PostApiAuthRegisterResult = AxiosResponse<void>
export type PostApiAuthLoginResult = AxiosResponse<void>
