/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  IngredientDto
} from '../../model';


export const getGetApiIngredientIdResponseMock = (): IngredientDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), isAllergen: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), isMeat: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])})))

export const getPostApiIngredientResponseMock = (overrideResponse: Partial< IngredientDto > = {}): IngredientDto => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), isAllergen: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), isMeat: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), ...overrideResponse})

export const getGetApiIngredientGetAllResponseMock = (): IngredientDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), isAllergen: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), isMeat: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])})))


export const getGetApiIngredientIdMockHandler = (overrideResponse?: IngredientDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<IngredientDto[]> | IngredientDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/Ingredient/:id', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiIngredientIdResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}

export const getPostApiIngredientMockHandler = (overrideResponse?: IngredientDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<IngredientDto> | IngredientDto), options?: RequestHandlerOptions) => {
  return http.post('*/api/Ingredient', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiIngredientResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}

export const getGetApiIngredientGetAllMockHandler = (overrideResponse?: IngredientDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<IngredientDto[]> | IngredientDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/Ingredient/GetAll', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiIngredientGetAllResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}
export const getIngredientMock = () => [
  getGetApiIngredientIdMockHandler(),
  getPostApiIngredientMockHandler(),
  getGetApiIngredientGetAllMockHandler()]
