/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateIngredientDto,
  IngredientDto
} from '../../model';

import { customInstance } from '../../axiosConfig';



  export const getIngredient = () => {
const getApiIngredientId = (
    id: string,
 ) => {
      return customInstance<IngredientDto[]>(
      {url: `/api/Ingredient/${id}`, method: 'GET'
    },
      );
    }
  const postApiIngredient = (
    createIngredientDto: CreateIngredientDto,
 ) => {
      return customInstance<IngredientDto>(
      {url: `/api/Ingredient`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createIngredientDto
    },
      );
    }
  const getApiIngredientGetAll = (
    
 ) => {
      return customInstance<IngredientDto[]>(
      {url: `/api/Ingredient/GetAll`, method: 'GET'
    },
      );
    }
  return {getApiIngredientId,postApiIngredient,getApiIngredientGetAll}};
export type GetApiIngredientIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getIngredient>['getApiIngredientId']>>>
export type PostApiIngredientResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getIngredient>['postApiIngredient']>>>
export type GetApiIngredientGetAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getIngredient>['getApiIngredientGetAll']>>>
