/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateIngredientDto,
  IngredientDto
} from '../../model';




  export const getIngredient = () => {
const getApiIngredientId = <TData = AxiosResponse<IngredientDto[]>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Ingredient/${id}`,options
    );
  }
const postApiIngredient = <TData = AxiosResponse<IngredientDto>>(
    createIngredientDto: CreateIngredientDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/Ingredient`,
      createIngredientDto,options
    );
  }
const getApiIngredientGetAll = <TData = AxiosResponse<IngredientDto[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Ingredient/GetAll`,options
    );
  }
return {getApiIngredientId,postApiIngredient,getApiIngredientGetAll}};
export type GetApiIngredientIdResult = AxiosResponse<IngredientDto[]>
export type PostApiIngredientResult = AxiosResponse<IngredientDto>
export type GetApiIngredientGetAllResult = AxiosResponse<IngredientDto[]>
