/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  PizzaDetailsDto,
  PizzaSearchCriteriaDto,
  PizzaSearchResultDto,
  PostApiPizzaBody,
  UpdatePizzaDto
} from '../../model';




  export const getPizza = () => {
const postApiPizza = <TData = AxiosResponse<void>>(
    postApiPizzaBody: PostApiPizzaBody, options?: AxiosRequestConfig
 ): Promise<TData> => {const formUrlEncoded = new URLSearchParams();
if(postApiPizzaBody.IngredientIds !== undefined) {
 postApiPizzaBody.IngredientIds.forEach(value => formUrlEncoded.append(`IngredientIds`, value));
 }
if(postApiPizzaBody.Name !== undefined) {
 formUrlEncoded.append(`Name`, postApiPizzaBody.Name);
 }
if(postApiPizzaBody.Description !== undefined) {
 formUrlEncoded.append(`Description`, postApiPizzaBody.Description);
 }
if(postApiPizzaBody.Price !== undefined) {
 formUrlEncoded.append(`Price`, postApiPizzaBody.Price.toString())
 }
if(postApiPizzaBody.ImageUrl !== undefined) {
 formUrlEncoded.append(`ImageUrl`, postApiPizzaBody.ImageUrl);
 }
if(postApiPizzaBody.ImageFile !== undefined) {
 formUrlEncoded.append(`ImageFile`, postApiPizzaBody.ImageFile);
 }
if(postApiPizzaBody['Style.Id'] !== undefined) {
 formUrlEncoded.append(`Style.Id`, postApiPizzaBody['Style.Id']);
 }
if(postApiPizzaBody['Style.Name'] !== undefined) {
 formUrlEncoded.append(`Style.Name`, postApiPizzaBody['Style.Name']);
 }
if(postApiPizzaBody['BaseSauce.Id'] !== undefined) {
 formUrlEncoded.append(`BaseSauce.Id`, postApiPizzaBody['BaseSauce.Id']);
 }
if(postApiPizzaBody['BaseSauce.Name'] !== undefined) {
 formUrlEncoded.append(`BaseSauce.Name`, postApiPizzaBody['BaseSauce.Name']);
 }
if(postApiPizzaBody['Dough.Id'] !== undefined) {
 formUrlEncoded.append(`Dough.Id`, postApiPizzaBody['Dough.Id']);
 }
if(postApiPizzaBody['Dough.Name'] !== undefined) {
 formUrlEncoded.append(`Dough.Name`, postApiPizzaBody['Dough.Name']);
 }
if(postApiPizzaBody['Thickness.Id'] !== undefined) {
 formUrlEncoded.append(`Thickness.Id`, postApiPizzaBody['Thickness.Id']);
 }
if(postApiPizzaBody['Thickness.Name'] !== undefined) {
 formUrlEncoded.append(`Thickness.Name`, postApiPizzaBody['Thickness.Name']);
 }
if(postApiPizzaBody['Shape.Id'] !== undefined) {
 formUrlEncoded.append(`Shape.Id`, postApiPizzaBody['Shape.Id']);
 }
if(postApiPizzaBody['Shape.Name'] !== undefined) {
 formUrlEncoded.append(`Shape.Name`, postApiPizzaBody['Shape.Name']);
 }
if(postApiPizzaBody.DiameterCm !== undefined) {
 formUrlEncoded.append(`DiameterCm`, postApiPizzaBody.DiameterCm.toString())
 }
if(postApiPizzaBody.WidthCm !== undefined) {
 formUrlEncoded.append(`WidthCm`, postApiPizzaBody.WidthCm.toString())
 }
if(postApiPizzaBody.LengthCm !== undefined) {
 formUrlEncoded.append(`LengthCm`, postApiPizzaBody.LengthCm.toString())
 }
if(postApiPizzaBody.WeightGrams !== undefined) {
 formUrlEncoded.append(`WeightGrams`, postApiPizzaBody.WeightGrams.toString())
 }
if(postApiPizzaBody.Kcal !== undefined) {
 formUrlEncoded.append(`Kcal`, postApiPizzaBody.Kcal.toString())
 }
if(postApiPizzaBody.MenuId !== undefined) {
 formUrlEncoded.append(`MenuId`, postApiPizzaBody.MenuId);
 }

    return axios.default.post(
      `/api/Pizza`,
      formUrlEncoded,options
    );
  }
const getApiPizzaGetAll = <TData = AxiosResponse<PizzaSearchResultDto[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Pizza/GetAll`,options
    );
  }
const getApiPizzaId = <TData = AxiosResponse<PizzaDetailsDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Pizza/${id}`,options
    );
  }
const putApiPizzaId = <TData = AxiosResponse<void>>(
    id: string,
    updatePizzaDto: UpdatePizzaDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/Pizza/${id}`,
      updatePizzaDto,options
    );
  }
const deleteApiPizzaId = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/Pizza/${id}`,options
    );
  }
const postApiPizzaSearch = <TData = AxiosResponse<PizzaSearchResultDto[]>>(
    pizzaSearchCriteriaDto: PizzaSearchCriteriaDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/Pizza/search`,
      pizzaSearchCriteriaDto,options
    );
  }
return {postApiPizza,getApiPizzaGetAll,getApiPizzaId,putApiPizzaId,deleteApiPizzaId,postApiPizzaSearch}};
export type PostApiPizzaResult = AxiosResponse<void>
export type GetApiPizzaGetAllResult = AxiosResponse<PizzaSearchResultDto[]>
export type GetApiPizzaIdResult = AxiosResponse<PizzaDetailsDto>
export type PutApiPizzaIdResult = AxiosResponse<void>
export type DeleteApiPizzaIdResult = AxiosResponse<void>
export type PostApiPizzaSearchResult = AxiosResponse<PizzaSearchResultDto[]>
