/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreatePizzaDto,
  GetApiPizzaSearchParams,
  PizzaDetailsDto,
  PizzaSearchResultDto,
  UpdatePizzaDto
} from '../../model';




  export const getPizza = () => {
const postApiPizza = <TData = AxiosResponse<void>>(
    createPizzaDto: CreatePizzaDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/Pizza`,
      createPizzaDto,options
    );
  }
const getApiPizzaGetAll = <TData = AxiosResponse<PizzaSearchResultDto[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Pizza/GetAll`,options
    );
  }
const getApiPizzaId = <TData = AxiosResponse<PizzaDetailsDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Pizza/${id}`,options
    );
  }
const putApiPizzaId = <TData = AxiosResponse<void>>(
    id: string,
    updatePizzaDto: UpdatePizzaDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/Pizza/${id}`,
      updatePizzaDto,options
    );
  }
const deleteApiPizzaId = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/Pizza/${id}`,options
    );
  }
const getApiPizzaSearch = <TData = AxiosResponse<PizzaSearchResultDto[]>>(
    params?: GetApiPizzaSearchParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Pizza/search`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {postApiPizza,getApiPizzaGetAll,getApiPizzaId,putApiPizzaId,deleteApiPizzaId,getApiPizzaSearch}};
export type PostApiPizzaResult = AxiosResponse<void>
export type GetApiPizzaGetAllResult = AxiosResponse<PizzaSearchResultDto[]>
export type GetApiPizzaIdResult = AxiosResponse<PizzaDetailsDto>
export type PutApiPizzaIdResult = AxiosResponse<void>
export type DeleteApiPizzaIdResult = AxiosResponse<void>
export type GetApiPizzaSearchResult = AxiosResponse<PizzaSearchResultDto[]>
