/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import type { City } from './city';

export interface Address {
  id?: string;
  street: string;
  buildingNumber: string;
  /** @nullable */
  apartmentNumber?: string | null;
  zipCode: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  latitude?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  longitude?: number | string;
  cityId?: string;
  city?: null | City;
}
