/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CityDto {
  id?: string;
  name: string;
  region: string;
  countryId?: string;
  /** @nullable */
  countryName?: string | null;
}
