/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CrustThicknessEnum } from './crustThicknessEnum';
import type { DoughTypeEnum } from './doughTypeEnum';
import type { IFormFile } from './iFormFile';
import type { PizzaShapeEnum } from './pizzaShapeEnum';
import type { PizzaStyleEnum } from './pizzaStyleEnum';
import type { SauceTypeEnum } from './sauceTypeEnum';

export interface CreatePizzaDto {
  ingredientIds?: string[];
  /** @maxLength 100 */
  name: string;
  /** @nullable */
  description?: string | null;
  /**
   * @minimum 0.01
   * @maximum 10000
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
   */
  price?: number | string;
  /** @nullable */
  imageUrl?: string | null;
  imageFile?: null | IFormFile | null;
  style: PizzaStyleEnum;
  baseSauce: SauceTypeEnum;
  dough: DoughTypeEnum;
  thickness: CrustThicknessEnum;
  shape: PizzaShapeEnum;
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
   */
  diameterCm?: number | string | null;
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
   */
  widthCm?: number | string | null;
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
   */
  lengthCm?: number | string | null;
  /**
   * @minimum 1
   * @maximum 10000
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
   */
  weightGrams?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  kcal?: number | string;
  menuId: string;
}
