/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PizzeriaAddressRequest } from './pizzeriaAddressRequest';

export interface CreatePizzeriaDto {
  brandId: string;
  /** @maxLength 100 */
  name: string;
  phoneNumber: string;
  /**
   * @minimum 0
   * @maximum 1000
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
   */
  deliveryCost?: number | string;
  /**
   * @minimum 0
   * @maximum 10000
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
   */
  minOrderAmount?: number | string;
  /**
   * @minimum 0
   * @maximum 100
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
   */
  serviceFee?: number | string;
  /**
   * @minimum 1
   * @maximum 120
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  averagePreparationTimeMinutes?: number | string;
  /**
   * @minimum 0
   * @maximum 100
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$
   */
  maxDeliveryRange?: number | string;
  address: PizzeriaAddressRequest;
}
