/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CrustThicknessEnum } from './crustThicknessEnum';
import type { DoughTypeEnum } from './doughTypeEnum';
import type { PizzaShapeEnum } from './pizzaShapeEnum';
import type { PizzaStyleEnum } from './pizzaStyleEnum';
import type { SauceTypeEnum } from './sauceTypeEnum';
import type { SortOptionEnum } from './sortOptionEnum';

export type GetApiPizzaSearchParams = {
CityId?: string;
BrandIds?: string[];
Styles?: PizzaStyleEnum[];
Doughs?: DoughTypeEnum[];
Thicknesses?: CrustThicknessEnum[];
Shapes?: PizzaShapeEnum[];
Sauces?: SauceTypeEnum[];
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
 */
MinPrice?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
 */
MaxPrice?: number | string;
SortBy?: SortOptionEnum;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
PageNumber?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
PageSize?: number | string;
};
