/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LookUpItemDto } from './lookUpItemDto';
import type { SortOptionEnum } from './sortOptionEnum';

export interface PizzaSearchCriteriaDto {
  cityId: string;
  /** @nullable */
  brandIds?: string[] | null;
  /** @nullable */
  styles?: LookUpItemDto[] | null;
  /** @nullable */
  doughs?: LookUpItemDto[] | null;
  /** @nullable */
  thicknesses?: LookUpItemDto[] | null;
  /** @nullable */
  shapes?: LookUpItemDto[] | null;
  /** @nullable */
  sauces?: LookUpItemDto[] | null;
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
   */
  minPrice?: number | string | null;
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
   */
  maxPrice?: number | string | null;
  sortBy?: SortOptionEnum;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageNumber?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize?: number | string;
}
