/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */

export interface PizzaSearchResultDto {
  id?: string;
  name: string;
  /** @nullable */
  description?: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  price?: number | string;
  /** @nullable */
  imageUrl?: string | null;
  ingredientNames?: string[];
}
