/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */

export interface PizzeriaSimpleDto {
  id?: string;
  name: string;
  /** @nullable */
  city?: string | null;
}
