/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LookUpItemDto } from './lookUpItemDto';

export interface PizzaFiltersDto {
  restaurants?: LookUpItemDto[];
  styles?: LookUpItemDto[];
  doughs?: LookUpItemDto[];
  thicknesses?: LookUpItemDto[];
  shapes?: LookUpItemDto[];
  sauces?: LookUpItemDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  maxPriceLimit?: number | string;
}
