/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterDto {
  email: string;
  /** @minLength 6 */
  password: string;
  firstName: string;
  lastName: string;
  isOwner?: boolean;
  /** @nullable */
  taxId?: string | null;
}
