/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */

export interface WorkScheduleDto {
  id?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  dayOfWeek?: number | string;
  /** @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$ */
  openTime?: string;
  /** @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$ */
  closeTime?: string;
  pizzeriaId?: string;
  /** @nullable */
  pizzeriaName?: string | null;
}
