/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  BrandDetailsDto,
  BrandDto,
  PostApiBrandBody
} from '../../model';

import { customInstance } from '../../axiosConfig';



  export const getBrand = () => {
const getApiBrandGetAll = (
    
 ) => {
      return customInstance<BrandDto[]>(
      {url: `/api/Brand/GetAll`, method: 'GET'
    },
      );
    }
  const getApiBrandId = (
    id: string,
 ) => {
      return customInstance<BrandDetailsDto>(
      {url: `/api/Brand/${id}`, method: 'GET'
    },
      );
    }
  const deleteApiBrandId = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/api/Brand/${id}`, method: 'DELETE'
    },
      );
    }
  const postApiBrand = (
    postApiBrandBody: PostApiBrandBody,
 ) => {const formUrlEncoded = new URLSearchParams();
if(postApiBrandBody.Name !== undefined) {
 formUrlEncoded.append(`Name`, postApiBrandBody.Name);
 }
if(postApiBrandBody.LogoFile !== undefined) {
 formUrlEncoded.append(`LogoFile`, postApiBrandBody.LogoFile);
 }

      return customInstance<void>(
      {url: `/api/Brand`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded
    },
      );
    }
  return {getApiBrandGetAll,getApiBrandId,deleteApiBrandId,postApiBrand}};
export type GetApiBrandGetAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBrand>['getApiBrandGetAll']>>>
export type GetApiBrandIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBrand>['getApiBrandId']>>>
export type DeleteApiBrandIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBrand>['deleteApiBrandId']>>>
export type PostApiBrandResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBrand>['postApiBrand']>>>
