/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  BrandDetailsDto,
  BrandDto
} from '../../model';


export const getGetApiBrandResponseMock = (): BrandDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}})})))

export const getGetApiBrandIdResponseMock = (overrideResponse: Partial< BrandDetailsDto > = {}): BrandDetailsDto => ({logo: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), pizzerias: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), city: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined])})), undefined]), id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getPostApiBrandMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/Brand', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getGetApiBrandMockHandler = (overrideResponse?: BrandDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<BrandDto[]> | BrandDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/Brand', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiBrandResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}

export const getGetApiBrandIdMockHandler = (overrideResponse?: BrandDetailsDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<BrandDetailsDto> | BrandDetailsDto), options?: RequestHandlerOptions) => {
  return http.get('*/api/Brand/:id', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiBrandIdResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}

export const getDeleteApiBrandIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/Brand/:id', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}
export const getBrandMock = () => [
  getPostApiBrandMockHandler(),
  getGetApiBrandMockHandler(),
  getGetApiBrandIdMockHandler(),
  getDeleteApiBrandIdMockHandler()]
