/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  BrandDetailsDto,
  BrandDto,
  CreateBrandDto
} from '../../model';




  export const getBrand = () => {
const postApiBrand = <TData = AxiosResponse<void>>(
    createBrandDto: CreateBrandDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/Brand`,
      createBrandDto,options
    );
  }
const getApiBrand = <TData = AxiosResponse<BrandDto[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Brand`,options
    );
  }
const getApiBrandId = <TData = AxiosResponse<BrandDetailsDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/Brand/${id}`,options
    );
  }
const deleteApiBrandId = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/Brand/${id}`,options
    );
  }
return {postApiBrand,getApiBrand,getApiBrandId,deleteApiBrandId}};
export type PostApiBrandResult = AxiosResponse<void>
export type GetApiBrandResult = AxiosResponse<BrandDto[]>
export type GetApiBrandIdResult = AxiosResponse<BrandDetailsDto>
export type DeleteApiBrandIdResult = AxiosResponse<void>
