/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CityDto
} from '../../model';


export const getGetApiCityIdResponseMock = (overrideResponse: Partial< CityDto > = {}): CityDto => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), region: faker.string.alpha({length: {min: 10, max: 20}}), countryId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), countryName: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), ...overrideResponse})

export const getPostApiCityResponseMock = (overrideResponse: Partial< CityDto > = {}): CityDto => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), region: faker.string.alpha({length: {min: 10, max: 20}}), countryId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), countryName: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), ...overrideResponse})

export const getGetApiCityGetAllResponseMock = (): CityDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), region: faker.string.alpha({length: {min: 10, max: 20}}), countryId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), countryName: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined])})))

export const getGetApiCityGetByCountryCountryIdResponseMock = (): CityDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), region: faker.string.alpha({length: {min: 10, max: 20}}), countryId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), countryName: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined])})))


export const getGetApiCityIdMockHandler = (overrideResponse?: CityDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CityDto> | CityDto), options?: RequestHandlerOptions) => {
  return http.get('*/api/City/:id', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiCityIdResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}

export const getPutApiCityIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/api/City/:id', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getDeleteApiCityIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/City/:id', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getPostApiCityMockHandler = (overrideResponse?: CityDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CityDto> | CityDto), options?: RequestHandlerOptions) => {
  return http.post('*/api/City', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiCityResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}

export const getGetApiCityGetAllMockHandler = (overrideResponse?: CityDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CityDto[]> | CityDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/City/GetAll', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiCityGetAllResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}

export const getGetApiCityGetByCountryCountryIdMockHandler = (overrideResponse?: CityDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CityDto[]> | CityDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/City/GetByCountry/:countryId', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiCityGetByCountryCountryIdResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}
export const getCityMock = () => [
  getGetApiCityIdMockHandler(),
  getPutApiCityIdMockHandler(),
  getDeleteApiCityIdMockHandler(),
  getPostApiCityMockHandler(),
  getGetApiCityGetAllMockHandler(),
  getGetApiCityGetByCountryCountryIdMockHandler()]
