/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CityDto,
  CreateCityDto,
  UpdateCityDto
} from '../../model';




  export const getCity = () => {
const getApiCityId = <TData = AxiosResponse<CityDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/City/${id}`,options
    );
  }
const putApiCityId = <TData = AxiosResponse<void>>(
    id: string,
    updateCityDto: UpdateCityDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/City/${id}`,
      updateCityDto,options
    );
  }
const deleteApiCityId = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/City/${id}`,options
    );
  }
const postApiCity = <TData = AxiosResponse<CityDto>>(
    createCityDto: CreateCityDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/City`,
      createCityDto,options
    );
  }
const getApiCityGetAll = <TData = AxiosResponse<CityDto[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/City/GetAll`,options
    );
  }
const getApiCityGetByCountryCountryId = <TData = AxiosResponse<CityDto[]>>(
    countryId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/City/GetByCountry/${countryId}`,options
    );
  }
return {getApiCityId,putApiCityId,deleteApiCityId,postApiCity,getApiCityGetAll,getApiCityGetByCountryCountryId}};
export type GetApiCityIdResult = AxiosResponse<CityDto>
export type PutApiCityIdResult = AxiosResponse<void>
export type DeleteApiCityIdResult = AxiosResponse<void>
export type PostApiCityResult = AxiosResponse<CityDto>
export type GetApiCityGetAllResult = AxiosResponse<CityDto[]>
export type GetApiCityGetByCountryCountryIdResult = AxiosResponse<CityDto[]>
