/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  CityDto,
  CreateCityDto,
  UpdateCityDto
} from '../../model';

import { customInstance } from '../../axiosConfig';



  export const getCity = () => {
const getApiCityId = (
    id: string,
 ) => {
      return customInstance<CityDto>(
      {url: `/api/City/${id}`, method: 'GET'
    },
      );
    }
  const putApiCityId = (
    id: string,
    updateCityDto: UpdateCityDto,
 ) => {
      return customInstance<void>(
      {url: `/api/City/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCityDto
    },
      );
    }
  const deleteApiCityId = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/api/City/${id}`, method: 'DELETE'
    },
      );
    }
  const postApiCity = (
    createCityDto: CreateCityDto,
 ) => {
      return customInstance<CityDto>(
      {url: `/api/City`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCityDto
    },
      );
    }
  const getApiCityGetAll = (
    
 ) => {
      return customInstance<CityDto[]>(
      {url: `/api/City/GetAll`, method: 'GET'
    },
      );
    }
  const getApiCityGetByCountryCountryId = (
    countryId: string,
 ) => {
      return customInstance<CityDto[]>(
      {url: `/api/City/GetByCountry/${countryId}`, method: 'GET'
    },
      );
    }
  return {getApiCityId,putApiCityId,deleteApiCityId,postApiCity,getApiCityGetAll,getApiCityGetByCountryCountryId}};
export type GetApiCityIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCity>['getApiCityId']>>>
export type PutApiCityIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCity>['putApiCityId']>>>
export type DeleteApiCityIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCity>['deleteApiCityId']>>>
export type PostApiCityResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCity>['postApiCity']>>>
export type GetApiCityGetAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCity>['getApiCityGetAll']>>>
export type GetApiCityGetByCountryCountryIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getCity>['getApiCityGetByCountryCountryId']>>>
