/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateWorkScheduleDto,
  UpdateWorkScheduleDto,
  WorkScheduleDto
} from '../../model';

import { customInstance } from '../../axiosConfig';



  export const getWorkSchedule = () => {
const getApiWorkScheduleGetByPizzeriaPizzeriaId = (
    pizzeriaId: string,
 ) => {
      return customInstance<WorkScheduleDto[]>(
      {url: `/api/WorkSchedule/GetByPizzeria/${pizzeriaId}`, method: 'GET'
    },
      );
    }
  const getApiWorkScheduleId = (
    id: string,
 ) => {
      return customInstance<WorkScheduleDto>(
      {url: `/api/WorkSchedule/${id}`, method: 'GET'
    },
      );
    }
  const putApiWorkScheduleId = (
    id: string,
    updateWorkScheduleDto: UpdateWorkScheduleDto,
 ) => {
      return customInstance<void>(
      {url: `/api/WorkSchedule/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateWorkScheduleDto
    },
      );
    }
  const deleteApiWorkScheduleId = (
    id: string,
 ) => {
      return customInstance<void>(
      {url: `/api/WorkSchedule/${id}`, method: 'DELETE'
    },
      );
    }
  const postApiWorkSchedule = (
    createWorkScheduleDto: CreateWorkScheduleDto,
 ) => {
      return customInstance<WorkScheduleDto>(
      {url: `/api/WorkSchedule`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWorkScheduleDto
    },
      );
    }
  return {getApiWorkScheduleGetByPizzeriaPizzeriaId,getApiWorkScheduleId,putApiWorkScheduleId,deleteApiWorkScheduleId,postApiWorkSchedule}};
export type GetApiWorkScheduleGetByPizzeriaPizzeriaIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkSchedule>['getApiWorkScheduleGetByPizzeriaPizzeriaId']>>>
export type GetApiWorkScheduleIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkSchedule>['getApiWorkScheduleId']>>>
export type PutApiWorkScheduleIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkSchedule>['putApiWorkScheduleId']>>>
export type DeleteApiWorkScheduleIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkSchedule>['deleteApiWorkScheduleId']>>>
export type PostApiWorkScheduleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWorkSchedule>['postApiWorkSchedule']>>>
