/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  WorkScheduleDto
} from '../../model';


export const getGetApiWorkScheduleGetByPizzeriaPizzeriaIdResponseMock = (): WorkScheduleDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), dayOfWeek: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),faker.string.alpha({length: {min: 10, max: 20}}),]), undefined]), openTime: faker.helpers.arrayElement([faker.helpers.fromRegExp('^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$'), undefined]), closeTime: faker.helpers.arrayElement([faker.helpers.fromRegExp('^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$'), undefined]), pizzeriaId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), pizzeriaName: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined])})))

export const getGetApiWorkScheduleIdResponseMock = (overrideResponse: Partial< WorkScheduleDto > = {}): WorkScheduleDto => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), dayOfWeek: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),faker.string.alpha({length: {min: 10, max: 20}}),]), undefined]), openTime: faker.helpers.arrayElement([faker.helpers.fromRegExp('^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$'), undefined]), closeTime: faker.helpers.arrayElement([faker.helpers.fromRegExp('^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$'), undefined]), pizzeriaId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), pizzeriaName: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), ...overrideResponse})

export const getPostApiWorkScheduleResponseMock = (overrideResponse: Partial< WorkScheduleDto > = {}): WorkScheduleDto => ({id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), dayOfWeek: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),faker.string.alpha({length: {min: 10, max: 20}}),]), undefined]), openTime: faker.helpers.arrayElement([faker.helpers.fromRegExp('^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$'), undefined]), closeTime: faker.helpers.arrayElement([faker.helpers.fromRegExp('^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$'), undefined]), pizzeriaId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), pizzeriaName: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), ...overrideResponse})


export const getGetApiWorkScheduleGetByPizzeriaPizzeriaIdMockHandler = (overrideResponse?: WorkScheduleDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<WorkScheduleDto[]> | WorkScheduleDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/WorkSchedule/GetByPizzeria/:pizzeriaId', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiWorkScheduleGetByPizzeriaPizzeriaIdResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}

export const getGetApiWorkScheduleIdMockHandler = (overrideResponse?: WorkScheduleDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<WorkScheduleDto> | WorkScheduleDto), options?: RequestHandlerOptions) => {
  return http.get('*/api/WorkSchedule/:id', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiWorkScheduleIdResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}

export const getPutApiWorkScheduleIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/api/WorkSchedule/:id', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getDeleteApiWorkScheduleIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/WorkSchedule/:id', async (info) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}

export const getPostApiWorkScheduleMockHandler = (overrideResponse?: WorkScheduleDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<WorkScheduleDto> | WorkScheduleDto), options?: RequestHandlerOptions) => {
  return http.post('*/api/WorkSchedule', async (info) => {
  
    return new HttpResponse(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiWorkScheduleResponseMock(),
      { status: 200,
        headers: { 'Content-Type': 'text/plain' }
      })
  }, options)
}
export const getWorkScheduleMock = () => [
  getGetApiWorkScheduleGetByPizzeriaPizzeriaIdMockHandler(),
  getGetApiWorkScheduleIdMockHandler(),
  getPutApiWorkScheduleIdMockHandler(),
  getDeleteApiWorkScheduleIdMockHandler(),
  getPostApiWorkScheduleMockHandler()]
