/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * PizzaApp | v1
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateWorkScheduleDto,
  UpdateWorkScheduleDto,
  WorkScheduleDto
} from '../../model';




  export const getWorkSchedule = () => {
const getApiWorkScheduleGetByPizzeriaPizzeriaId = <TData = AxiosResponse<WorkScheduleDto[]>>(
    pizzeriaId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/WorkSchedule/GetByPizzeria/${pizzeriaId}`,options
    );
  }
const getApiWorkScheduleId = <TData = AxiosResponse<WorkScheduleDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/WorkSchedule/${id}`,options
    );
  }
const putApiWorkScheduleId = <TData = AxiosResponse<void>>(
    id: string,
    updateWorkScheduleDto: UpdateWorkScheduleDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/WorkSchedule/${id}`,
      updateWorkScheduleDto,options
    );
  }
const deleteApiWorkScheduleId = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/WorkSchedule/${id}`,options
    );
  }
const postApiWorkSchedule = <TData = AxiosResponse<WorkScheduleDto>>(
    createWorkScheduleDto: CreateWorkScheduleDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/WorkSchedule`,
      createWorkScheduleDto,options
    );
  }
return {getApiWorkScheduleGetByPizzeriaPizzeriaId,getApiWorkScheduleId,putApiWorkScheduleId,deleteApiWorkScheduleId,postApiWorkSchedule}};
export type GetApiWorkScheduleGetByPizzeriaPizzeriaIdResult = AxiosResponse<WorkScheduleDto[]>
export type GetApiWorkScheduleIdResult = AxiosResponse<WorkScheduleDto>
export type PutApiWorkScheduleIdResult = AxiosResponse<void>
export type DeleteApiWorkScheduleIdResult = AxiosResponse<void>
export type PostApiWorkScheduleResult = AxiosResponse<WorkScheduleDto>
